// Code generated by MockGen. DO NOT EDIT.
// Source: ./payment/payment.go

// Package mock_payment is a generated GoMock package.
package mock_payment

import (
	context "context"
	payment "joshua-golang-training-beginner/payment"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPaymentCodeRepository is a mock of IPaymentCodeRepository interface.
type MockIPaymentCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentCodeRepositoryMockRecorder
}

// MockIPaymentCodeRepositoryMockRecorder is the mock recorder for MockIPaymentCodeRepository.
type MockIPaymentCodeRepositoryMockRecorder struct {
	mock *MockIPaymentCodeRepository
}

// NewMockIPaymentCodeRepository creates a new mock instance.
func NewMockIPaymentCodeRepository(ctrl *gomock.Controller) *MockIPaymentCodeRepository {
	mock := &MockIPaymentCodeRepository{ctrl: ctrl}
	mock.recorder = &MockIPaymentCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentCodeRepository) EXPECT() *MockIPaymentCodeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPaymentCodeRepository) Create(ctx context.Context, p *payment.PaymentCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIPaymentCodeRepositoryMockRecorder) Create(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPaymentCodeRepository)(nil).Create), ctx, p)
}

// GetByID mocks base method.
func (m *MockIPaymentCodeRepository) GetByID(ctx context.Context, id string) (payment.PaymentCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(payment.PaymentCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIPaymentCodeRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIPaymentCodeRepository)(nil).GetByID), ctx, id)
}

// MockIPaymentCodeService is a mock of IPaymentCodeService interface.
type MockIPaymentCodeService struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentCodeServiceMockRecorder
}

// MockIPaymentCodeServiceMockRecorder is the mock recorder for MockIPaymentCodeService.
type MockIPaymentCodeServiceMockRecorder struct {
	mock *MockIPaymentCodeService
}

// NewMockIPaymentCodeService creates a new mock instance.
func NewMockIPaymentCodeService(ctrl *gomock.Controller) *MockIPaymentCodeService {
	mock := &MockIPaymentCodeService{ctrl: ctrl}
	mock.recorder = &MockIPaymentCodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentCodeService) EXPECT() *MockIPaymentCodeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPaymentCodeService) Create(ctx context.Context, p *payment.PaymentCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIPaymentCodeServiceMockRecorder) Create(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPaymentCodeService)(nil).Create), ctx, p)
}

// GetByID mocks base method.
func (m *MockIPaymentCodeService) GetByID(ctx context.Context, id string) (payment.PaymentCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(payment.PaymentCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIPaymentCodeServiceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIPaymentCodeService)(nil).GetByID), ctx, id)
}
